USE loot_table_db;

INSERT INTO magic_item (magic_item_name, magic_item_type, magic_item_url, sourcebook_id)
    VALUES ("Armblade (Battleaxe)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Club)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Dagger)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Flail)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Handaxe)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Javelin)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Lance)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Light Hammer)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Longsword)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Mace)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Morningstar)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Quarterstaff)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Rapier)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Scimitar)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Shortsword)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Sickle)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Spear)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Trident)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (War Pick)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Warhammer)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Whip)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armblade (Yklwa)", "Weapon", "https://www.dndbeyond.com/magic-items/215692-armblade", NULL),
    ("Armor of Gleaming, Breastplate", "Armor", "https://www.dndbeyond.com/magic-items/36571-armor-of-gleaming", NULL),
    ("Armor of Gleaming, Chain Mail", "Armor", "https://www.dndbeyond.com/magic-items/36571-armor-of-gleaming", NULL),
    ("Armor of Gleaming, Chain Shirt", "Armor", "https://www.dndbeyond.com/magic-items/36571-armor-of-gleaming", NULL),
    ("Armor of Gleaming, Half Plate", "Armor", "https://www.dndbeyond.com/magic-items/36571-armor-of-gleaming", NULL),
    ("Armor of Gleaming, Hide", "Armor", "https://www.dndbeyond.com/magic-items/36571-armor-of-gleaming", NULL),
    ("Armor of Gleaming, Plate", "Armor", "https://www.dndbeyond.com/magic-items/36571-armor-of-gleaming", NULL),
    ("Armor of Gleaming, Ring Mail", "Armor", "https://www.dndbeyond.com/magic-items/36571-armor-of-gleaming", NULL),
    ("Armor of Gleaming, Scale Mail", "Armor", "https://www.dndbeyond.com/magic-items/36571-armor-of-gleaming", NULL),
    ("Armor of Gleaming, Spiked Armor", "Armor", "https://www.dndbeyond.com/magic-items/36571-armor-of-gleaming", NULL),
    ("Armor of Gleaming, Splint", "Armor", "https://www.dndbeyond.com/magic-items/36571-armor-of-gleaming", NULL),
    ("Arrows, Walloping", "Weapon", "https://www.dndbeyond.com/magic-items/36839-walloping-ammunition", NULL ),
    ("Band of Loyalty", "Ring", "https://www.dndbeyond.com/magic-items/215546-band-of-loyalty", NULL),
    ("Bead of Nourishment", "Wondrous Item", "https://www.dndbeyond.com/magic-items/27022-bead-of-nourishment", NULL)

    