-- MySQL Script generated by MySQL Workbench
-- Fri Feb 24 18:56:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DnD_loot_table` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DnD_loot_table` DEFAULT CHARACTER SET utf8 ;
USE `DnD_loot_table` ;

-- -----------------------------------------------------
-- Table `DnD_loot_table`.`sourcebook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DnD_loot_table`.`sourcebook` (
  `sourcebook_id` INT NOT NULL AUTO_INCREMENT,
  `sourcebook_name` VARCHAR(45) NULL,
  PRIMARY KEY (`sourcebook_id`),
  UNIQUE INDEX `sourcebook_id_UNIQUE` (`sourcebook_id` ASC) VISIBLE,
  UNIQUE INDEX `sourcebook_name_UNIQUE` (`sourcebook_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DnD_loot_table`.`magic_item_rarity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DnD_loot_table`.`magic_item_rarity` (
  `magic_item_rarity_id` INT NOT NULL AUTO_INCREMENT,
  `magic_item_rarity` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`magic_item_rarity_id`),
  UNIQUE INDEX `magic_item_rarity_id_UNIQUE` (`magic_item_rarity_id` ASC) VISIBLE,
  UNIQUE INDEX `magic_item_rarity_UNIQUE` (`magic_item_rarity` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DnD_loot_table`.`magic_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DnD_loot_table`.`magic_item` (
  `magic_item_id` INT NOT NULL AUTO_INCREMENT,
  `magic_item_name` VARCHAR(45) NOT NULL,
  `magic_item_type` VARCHAR(13) NOT NULL,
  `magic_item_rarity_id` INT NOT NULL,
  `magic_item_url` VARCHAR(100) NOT NULL,
  `sourcebook_id` INT NULL,
  PRIMARY KEY (`magic_item_id`),
  INDEX `fk_magic_item_sourcebooks_idx` (`sourcebook_id` ASC) VISIBLE,
  UNIQUE INDEX `magic_item_id_UNIQUE` (`magic_item_id` ASC) VISIBLE,
  UNIQUE INDEX `magic_item_name_UNIQUE` (`magic_item_name` ASC) VISIBLE,
  INDEX `fk_magic_item_magic_item_rarity1_idx` (`magic_item_rarity_id` ASC) VISIBLE,
  CONSTRAINT `fk_magic_item_sourcebooks`
    FOREIGN KEY (`sourcebook_id`)
    REFERENCES `DnD_loot_table`.`sourcebook` (`sourcebook_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_magic_item_magic_item_rarity1`
    FOREIGN KEY (`magic_item_rarity_id`)
    REFERENCES `DnD_loot_table`.`magic_item_rarity` (`magic_item_rarity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DnD_loot_table`.`attunement_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DnD_loot_table`.`attunement_class` (
  `attunement_class_id` INT NOT NULL AUTO_INCREMENT,
  `attunement_class` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`attunement_class_id`),
  UNIQUE INDEX `attunement_class_UNIQUE` (`attunement_class` ASC) VISIBLE,
  UNIQUE INDEX `attunement_class_id_UNIQUE` (`attunement_class_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DnD_loot_table`.`magic_item_has_attunement_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DnD_loot_table`.`magic_item_has_attunement_class` (
  `magic_item_id` INT NOT NULL,
  `attunement_class_id` INT NOT NULL,
  PRIMARY KEY (`magic_item_id`, `attunement_class_id`),
  INDEX `fk_magic_item_has_attunement_class_attunement_class1_idx` (`attunement_class_id` ASC) VISIBLE,
  INDEX `fk_magic_item_has_attunement_class_magic_item1_idx` (`magic_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_magic_item_has_attunement_class_magic_item1`
    FOREIGN KEY (`magic_item_id`)
    REFERENCES `DnD_loot_table`.`magic_item` (`magic_item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_magic_item_has_attunement_class_attunement_class1`
    FOREIGN KEY (`attunement_class_id`)
    REFERENCES `DnD_loot_table`.`attunement_class` (`attunement_class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
